name: build and deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Run chmod to make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./gradlew clean build

      - name: Build & Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/9kcal:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/9kcal:latest


  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to App Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Backend/tasteful-ai
            sudo docker-compose down
            sudo docker rm -f $(sudo docker ps -aq)  # 기존 컨테이너 삭제
            sudo docker rmi -f $(sudo docker images -q)  # 기존 이미지 삭제
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/9kcal:latest
            sudo docker-compose up -d --build
            sudo docker ps  # 실행 중인 컨테이너 확인